# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OsmParser
                                 A QGIS plugin
 Easy to parse OSM with AI!
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-28
        copyright            : (C) 2023 by Aino inc.
        email                : pulinetsag@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
API_LINK = "https://api.aino.world"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OsmParser class from file OsmParser.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .osm_parser import OsmParser
    return OsmParser(iface)
